require: rubocop-rspec

RSpec/NestedGroups:
  Max: 4

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/InheritException:
  EnforcedStyle: standard_error

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
Metrics/BlockLength:
  ExcludedMethods:
    - class_scope
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/LineLength:
  Max: 100

Performance/HashEachMethods:
  Enabled: false
